package com.thalesgroup.rtti._2017_10_01.ldb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-01-29T11:34:29.886Z
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/", name = "LDBServiceSoap")
@XmlSeeAlso({com.thalesgroup.rtti._2017_10_01.ldb.commontypes.ObjectFactory.class, com.thalesgroup.rtti._2007_10_10.ldb.commontypes.ObjectFactory.class, com.thalesgroup.rtti._2017_10_01.ldb.types.ObjectFactory.class, ObjectFactory.class, com.thalesgroup.rtti._2016_02_16.ldb.types.ObjectFactory.class, com.thalesgroup.rtti._2012_01_13.ldb.types.ObjectFactory.class, com.thalesgroup.rtti._2013_11_28.token.types.ObjectFactory.class, com.thalesgroup.rtti._2015_11_27.ldb.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LDBServiceSoap {

    @WebMethod(operationName = "GetDepartureBoard", action = "http://thalesgroup.com/RTTI/2012-01-13/ldb/GetDepartureBoard")
    @WebResult(name = "GetDepartureBoardResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/", partName = "parameters")
    public StationBoardResponseType getDepartureBoard(

        @WebParam(partName = "parameters", name = "GetDepartureBoardRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/")
        GetBoardRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetDepBoardWithDetails", action = "http://thalesgroup.com/RTTI/2015-05-14/ldb/GetDepBoardWithDetails")
    @WebResult(name = "GetDepBoardWithDetailsResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/", partName = "parameters")
    public StationBoardWithDetailsResponseType getDepBoardWithDetails(

        @WebParam(partName = "parameters", name = "GetDepBoardWithDetailsRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/")
        GetBoardRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetArrBoardWithDetails", action = "http://thalesgroup.com/RTTI/2015-05-14/ldb/GetArrBoardWithDetails")
    @WebResult(name = "GetArrBoardWithDetailsResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/", partName = "parameters")
    public StationBoardWithDetailsResponseType getArrBoardWithDetails(

        @WebParam(partName = "parameters", name = "GetArrBoardWithDetailsRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/")
        GetBoardRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetArrivalDepartureBoard", action = "http://thalesgroup.com/RTTI/2012-01-13/ldb/GetArrivalDepartureBoard")
    @WebResult(name = "GetArrivalDepartureBoardResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/", partName = "parameters")
    public StationBoardResponseType getArrivalDepartureBoard(

        @WebParam(partName = "parameters", name = "GetArrivalDepartureBoardRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/")
        GetBoardRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetNextDepartures", action = "http://thalesgroup.com/RTTI/2015-05-14/ldb/GetNextDepartures")
    @WebResult(name = "GetNextDeparturesResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/", partName = "parameters")
    public DeparturesBoardResponseType getNextDepartures(

        @WebParam(partName = "parameters", name = "GetNextDeparturesRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/")
        GetDeparturesRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetArrivalBoard", action = "http://thalesgroup.com/RTTI/2012-01-13/ldb/GetArrivalBoard")
    @WebResult(name = "GetArrivalBoardResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/", partName = "parameters")
    public StationBoardResponseType getArrivalBoard(

        @WebParam(partName = "parameters", name = "GetArrivalBoardRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/")
        GetBoardRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetArrDepBoardWithDetails", action = "http://thalesgroup.com/RTTI/2015-05-14/ldb/GetArrDepBoardWithDetails")
    @WebResult(name = "GetArrDepBoardWithDetailsResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/", partName = "parameters")
    public StationBoardWithDetailsResponseType getArrDepBoardWithDetails(

        @WebParam(partName = "parameters", name = "GetArrDepBoardWithDetailsRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/")
        GetBoardRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetFastestDeparturesWithDetails", action = "http://thalesgroup.com/RTTI/2015-05-14/ldb/GetFastestDeparturesWithDetails")
    @WebResult(name = "GetFastestDeparturesWithDetailsResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/", partName = "parameters")
    public DeparturesBoardWithDetailsResponseType getFastestDeparturesWithDetails(

        @WebParam(partName = "parameters", name = "GetFastestDeparturesWithDetailsRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/")
        GetDeparturesRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetFastestDepartures", action = "http://thalesgroup.com/RTTI/2015-05-14/ldb/GetFastestDepartures")
    @WebResult(name = "GetFastestDeparturesResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/", partName = "parameters")
    public DeparturesBoardResponseType getFastestDepartures(

        @WebParam(partName = "parameters", name = "GetFastestDeparturesRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/")
        GetDeparturesRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetServiceDetails", action = "http://thalesgroup.com/RTTI/2012-01-13/ldb/GetServiceDetails")
    @WebResult(name = "GetServiceDetailsResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/", partName = "parameters")
    public ServiceDetailsResponseType getServiceDetails(

        @WebParam(partName = "parameters", name = "GetServiceDetailsRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/")
        GetServiceDetailsRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetNextDeparturesWithDetails", action = "http://thalesgroup.com/RTTI/2015-05-14/ldb/GetNextDeparturesWithDetails")
    @WebResult(name = "GetNextDeparturesWithDetailsResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/", partName = "parameters")
    public DeparturesBoardWithDetailsResponseType getNextDeparturesWithDetails(

        @WebParam(partName = "parameters", name = "GetNextDeparturesWithDetailsRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/")
        GetDeparturesRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );
}
